### ISSUE TITLE
Conditional Attributes and Policies

### ISSUE THREAD

**Issue by viv012** [sagrawal87/ABE#13]
I want to create attributes and policies which are conditional in nature.

For instance:
Policy : AGE > 25
Attribute : AGE = 22

Decryption would not be possible in this case

How do I specify such attributes and policies?

**Comment by sagrawal87** [comment]
Page 7 of the [paper](https://www.cs.utexas.edu/users/bwaters/publications/papers/cp-abe.pdf) that introduced CP-ABE may help.
