### ISSUE TITLE
   how do I run this code on Ubuntu 20?

### ISSUE THREAD

**Issue by harshbisle** [sagrawal87/ABE#17]
@sagrawal87  @alexkorpas @codymlewis  please guide me I'm an absolute beginner

**Comment by sagrawal87** [comment]
Hi Harsh. Do the instructions provided in the prerequisites section (of the README file) not work for you?

**Comment by harshbisle** [comment]
Hello, @sagrawal87 Thanks for responding :) Readme file is not working out for me :(

**Comment by codymlewis** [comment]
Hi Harsh, at which point is it not working? Have you been able to install charm?

**Comment by harshbisle** [comment]
Hello, @codymlewis Thanks for responding :) Everything works fine until I give the make and make install command to install charm

**Comment by codymlewis** [comment]
So the issue is with charm crypto and not this?

**Comment by harshbisle** [comment]
Yes, but I expected a solution from here as somebody might have encountered it recently

**Comment by harshbisle** [comment]
please give any alternatives or some links to help me set up the environment

**Comment by codymlewis** [comment]
Fair enough, only issue I encountered with compiling Charm was the openssl version thing. Assuming you have the same issue, there are two possible solutions, install charm crypto from your system package manager (not sure if it is available on ubuntus apt however), or downgrade your openssl from version 1.1 to 1.0.

**Comment by harshbisle** [comment]
Yeah, I am facing the same issue, as you said is it not safe to downgrade the OpenSSL version from 1.1 to 1.0? and system package manager is not available on my machine :(

**Comment by codymlewis** [comment]
Hmm, I would not recommend downgrading openssl unless you're desperate. Maybe you could use a docker image? An arch linux image would have charm crypto in the AUR.

**Comment by harshbisle** [comment]
I'm not familiar with the docker image or arch Linux

**Comment by harshbisle** [comment]
Now I have installed charm crypto on VM VB but I don't know how to test the samples.
Is there any resource that I can refer to?

**Comment by codymlewis** [comment]
If you have python installed, you can just follow the README of this repository

**Comment by harshbisle** [comment]
```
rm -f -r pox3.egg-info/ dist/ build/
python3 setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
ImportError: No module named 'setuptools'
makefile:7: recipe for target 'setup' failed
make: *** [setup] Error 1
```
I got this when I make.

**Comment by codymlewis** [comment]
I see, could you try that again after running the following
~~~shell
pip install setuptools
~~~
