### ISSUE TITLE
error loading from charm.toolbox.pairinggroup import PairingGroup, GT

### ISSUE THREAD

**Issue by RomeyRome** [sagrawal87/ABE#3]
Hi,
I'm getting this error when I tied to run main.py

`Traceback (most recent call last):
File "main.py", line 6, in <module>
from charm.toolbox.pairinggroup import PairingGroup, GT`

I'm running Charm 0.43 and Python 2.7.10 on Mac OS X

**Comment by RockyZhangHKU** [comment]
Hi, I also meet this error on my Ubuntu, can not understand the reason. Have you fix this error already?

**Comment by RockyZhangHKU** [comment]
@RomeyRome Hi, I also meet this error on my Ubuntu, can not understand the reason. Have you fix this error already?
